[providers]
php = "8.2"

[phases.setup]
nixPkgs = ['php82', 'php82Extensions.pdo', 'php82Extensions.pdo_mysql', 'php82Extensions.mbstring', 'php82Extensions.xml', 'php82Extensions.curl', 'php82Extensions.zip', 'php82Extensions.gd', 'composer']

[phases.install]
cmds = ['composer install --no-dev --optimize-autoloader --no-scripts']

[phases.build]
cmds = ['php artisan config:clear', 'php artisan cache:clear']

[start]
cmd = 'php artisan migrate --force && php artisan config:cache && php artisan route:cache && php artisan serve --host=0.0.0.0 --port=$PORT'

[variables]
NIXPACKS_NO_MUSL = '1'
